name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install  # Ensures that dependencies are installed

      - name: Build the project
        run: npm run build

      - name: Deploy index.html to root of gh-pages
        run: |
          git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          cp ./index.html ./gh-pages/
          git -C gh-pages add index.html
          git -C gh-pages commit -m "Deploy index.html"
          git -C gh-pages push

      - name: Deploy dist folder to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
